/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline-variant": "#cfc6ab",
        "tertiary-fixed": "#ffdad3",
        "tertiary": "#ba1c00",
        "tertiary-container": "#ffd5cd",
        "secondary": "#0040e0",
        "error-container": "#ffdad6",
        "on-secondary-container": "#efefff",
        "inverse-primary": "#e3c600",
        "surface-container": "#f0edee",
        "tertiary-fixed-dim": "#ffb4a5",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#3e0400",
        "secondary-fixed": "#dde1ff",
        "on-tertiary-container": "#c01e00",
        "surface-dim": "#dcd9da",
        "on-tertiary": "#ffffff",
        "on-surface": "#1b1b1c",
        "on-surface-variant": "#4c4732",
        "on-secondary-fixed-variant": "#0035be",
        "surface-variant": "#e5e2e3",
        "secondary-fixed-dim": "#b8c3ff",
        "surface-container-highest": "#e5e2e3",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f3f0f1",
        "surface": "#fcf8f9",
        "on-secondary-fixed": "#001356",
        "primary-container": "#ffde00",
        "surface-tint": "#6d5e00",
        "on-primary-container": "#716200",
        "surface-container-lowest": "#ffffff",
        "background": "#fcf8f9",
        "on-tertiary-fixed-variant": "#8e1300",
        "on-primary-fixed-variant": "#524600",
        "on-secondary": "#ffffff",
        "surface-container-high": "#eae7e8",
        "primary-fixed": "#ffe24a",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#e3c600",
        "outline": "#7d775f",
        "on-error": "#ffffff",
        "secondary-container": "#2e5bff",
        "primary": "#6d5e00",
        "surface-bright": "#fcf8f9",
        "surface-container-low": "#f6f3f4",
        "on-background": "#1b1b1c",
        "on-primary-fixed": "#211b00",
        "inverse-surface": "#303031",
        // keep old custom colors just in case
        comicYellow: '#FFC82C',
        comicRed: '#FF2E2E',
        comicBlue: '#2B82F6',
        comicBlack: '#161616',
        comicWhite: '#F8F9FA'
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "border-thin": "1px",
        "margin": "40px",
        "gutter": "24px",
        "unit": "4px",
        "border-thick": "3px"
      },
      fontFamily: {
        "headline-lg": ["var(--font-space-grotesk)", "sans-serif"],
        "body-md": ["var(--font-work-sans)", "sans-serif"],
        "headline-xl": ["var(--font-space-grotesk)", "sans-serif"],
        "body-lg": ["var(--font-work-sans)", "sans-serif"],
        "headline-md": ["var(--font-space-grotesk)", "sans-serif"],
        "label-bold": ["var(--font-lexend)", "sans-serif"],
        "caption": ["var(--font-work-sans)", "sans-serif"],
        // keep old fonts just in case
        bangers: ['var(--font-bangers)', 'cursive'],
        comic: ['var(--font-comic-neue)', 'cursive', 'sans-serif'],
      },
      fontSize: {
        "headline-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-xl": ["80px", { "lineHeight": "1.0", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "body-lg": ["20px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-bold": ["14px", { "lineHeight": "1.0", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }]
      },
      boxShadow: {
        'comic': '8px 8px 0px 0px rgba(22,22,22,1)',
        'comic-hover': '4px 4px 0px 0px rgba(22,22,22,1)',
      },
      animation: {
        'spin-slow': 'spin 12s linear infinite',
      }
    },
  },
  plugins: [],
};
